In [1]:
import numpy as np

#### reshape

- Array의 shape의 크기를 변경함 (element의 갯수는 동일)  
  ex)  
  `array = [[1,2,5,8], [1,2,5,8]]` > reshape > `array = [1,2,5,8,1,2,5,8]`
  

In [2]:
test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [3]:
np.array(test_matrix).reshape(2,2,2)
# 2 x 2 x 2 행렬

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [22]:
test =np.array(test_matrix).reshape(8,)
test

array([1, 2, 3, 4, 1, 2, 5, 8])

In [33]:
test_re = test.reshape(-1, 1) # -1 : size를 기반으로 row 개수 선정
                              # 내 생각엔, -1은 나머지 행렬을 열거한 듯하다.
                              # 1차원 행렬을 2차원 행렬로 만들어줄 수 있다.
print(test_re)
print(test_re.ndim)

[[1]
 [2]
 [3]
 [4]
 [1]
 [2]
 [5]
 [8]]
2


In [34]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

In [35]:
print(np.array(test).reshape(4,-1)) # 4행을 축으로 나머지를 열거한다. 순서대로
print(np.array(test).reshape(4,-1).shape)

[[1 2]
 [3 4]
 [1 2]
 [5 8]]
(4, 2)


In [23]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [25]:
np.array(test_matrix).reshape(2,2,2).shape

(2, 2, 2)

#### flat or flatten()

- 다차원 array를 1차원 array로 변환

In [36]:
print(np.array(test_matrix).flatten())
test_matrix = [[[1,2,3,4], [1,2,5,8]], [[1,2,3,4], [1,2,5,8]]]
print(np.array(test_matrix).flatten())

[1 2 3 4 1 2 5 8]
[1 2 3 4 1 2 5 8 1 2 3 4 1 2 5 8]
