In [1]:
import numpy as np

In [2]:
test_exmaple = np.array([[1, 2, 3], [4.5, 5, 6]], int)
test_exmaple

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
test_exmaple[0][0]

1

In [4]:
test_exmaple[0,0] # 이거 대박이고만,,

1

In [5]:
test_exmaple[0,0] = 10 # Matrix 0,0 에 12 할당
test_exmaple

array([[10,  2,  3],
       [ 4,  5,  6]])

In [6]:
test_exmaple[0][0] = 5 # Matrix 0,0 에 12 할당
test_exmaple[0,0]

5

#### slicing

- List와 달리 행과 열 부분을 나눠서 slicing이 가능함
- Matrix의 부분 집합을 추출할 때 유용함
- numpy의 가장 강력한 기능 중 하나 !

In [14]:
test_exmaple = np.array([
    [1, 2, 5,8], [1, 2, 5,8],[1, 2, 5,8],[1, 2, 5,8]], int)
test_exmaple[:2,:] # row - 0 ~ 1까지, column - 전체

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [15]:
print(test_exmaple[:,1:3])
print(test_exmaple[1,:2]) 

[[2 5]
 [2 5]
 [2 5]
 [2 5]]
[1 2]


In [23]:
test_exmaple = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [1,2,3,4,5]], int)
test_exmaple[:,2:] # 전체 Row의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [ 3,  4,  5]])

In [24]:
test_exmaple[1,1:3] # 1 Row의 1열 ~ 2열

array([7, 8])

In [30]:
test_exmaple[1:3] # 1 Row ~ 2Row의 전체

array([[ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [31]:
a = np.arange(100).reshape(10,10)
a[:, -1].reshape(-1,1)

array([[ 9],
       [19],
       [29],
       [39],
       [49],
       [59],
       [69],
       [79],
       [89],
       [99]])