#### 행렬의 곱셈

 i번째 행벡터와 j번째 열벡터 사이의 내적을 성분으로 가지는 행렬

In [1]:
import numpy as np

In [2]:
X = np.array([[1,-2,3],
            [7,5,0],
            [-2,-3,2]])

In [3]:
Y = np.array([[1,-2],
            [7,5],
            [-2,-3]])

In [4]:
X @ Y

array([[-19, -21],
       [ 42,  11],
       [-27, -17]])

#### 행렬의 내적

 np.inner은 i번째 행벡터와 j번째 행벡터 사이의 내적 성분  
 수학에서 말하는 내적과 다르다.  
 X * (Y의 전치행렬)

In [11]:
X = np.array([[1,-2,3],
            [7,5,0],
            [-2,-3,2]])

In [12]:
Y = np.array([[0, 1, -1],
             [1, -1, 0]])

In [10]:
np.inner(X, Y)

array([[-5,  3],
       [ 5,  2],
       [-5,  1]])

####  행렬의 이해

 행렬은 벡터 공간에서 __연산자__ 로 이해한다.  
 행렬곱을 통해 벡터를 다른 차원의 공간으로 보낼 수 있다.  
 __패턴 추출 가능 & 데이터 압축 가능__  

#### 역행렬

 A의 연산을 거꾸로 되돌리는 행렬을 __역행렬__ 이라 부른다.  
 행과 열의 숫자가 같아야 하고 행렬식이 0이 아닌 경우에만 계산 가능

In [21]:
X = np.array([[1,-2,3],
              [7,5,0],
             [-2,-1,2]])

np.linalg.inv(X)

array([[ 0.21276596,  0.0212766 , -0.31914894],
       [-0.29787234,  0.17021277,  0.44680851],
       [ 0.06382979,  0.10638298,  0.40425532]])

In [26]:
a = X @ np.linalg.inv(X)
print(a)

[[ 1.00000000e+00 -1.38777878e-17  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-2.77555756e-17  0.00000000e+00  1.00000000e+00]]


#### 역행렬

 만일 역행렬을 계산할 수 없다면 __유사역행렬__ 또는 __무어-펜로즈 역행렬__ 을  
 사용한다.  
 **행의 개수와 열의 개수의 대소에 따라 계산식이 달라진다.**  
 행이 열보다 클 때는 유사 역행렬을 먼저 곱해준다.  
 열이 행보다 클 때는 유사 역행렬을 뒤에 곱해준다.  

In [32]:
Y = np.array([[0,1],
              [1,-1],
              [-2, 1]])

b = np.linalg.pinv(Y)
a = b @ Y
print(b, end="\n\n")
print(a)

[[ 5.00000000e-01  1.11022302e-16 -5.00000000e-01]
 [ 8.33333333e-01 -3.33333333e-01 -1.66666667e-01]]

[[ 1.00000000e+00 -2.22044605e-16]
 [ 1.11022302e-16  1.00000000e+00]]


#### 유사역행렬

 유사역행렬을 이용해서 연립 방정식의 해를 구할 수 있다.

## 선형회귀분석

In [34]:
# Scikit Learn 을 활용한 회귀 분석
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X,y)
y_test = model.predict(x_test)

# Moore-Penrose 역행렬
X_ = np.array([np.append(x,[1]) for x  in X])
beta = np.linalg.pinv(X_) @ y
y_test = np.append(x,[1]) @ beta

ModuleNotFoundError: No module named 'sklearn'