## Vector

 vector는 숫자를 원소로 가지는 리스트(list) 또는 배열(array)입니다.  
 vector는 공간에서 한 점을 나타냅니다.   
 vector는 원점으로부터 상대적 위치를 표현합니다.  
 vector에 숫자를 곱해주면 길이만 변화됩니다.  
 두 벡터의 덧셈은 다른 벡터로부터 상대적 위치이동을 표현합니다. (뺄셈은 반대 방향)

In [5]:
import numpy as np

In [6]:
x = np.array([1, 2, 3])
y = np.array([2, 3, 4])

In [7]:
print(x + y)
print(x - y)
print(x * y)

[3 5 7]
[-1 -1 -1]
[ 2  6 12]


## Vector의 노름 (norm)

 __원점에서부터의 거리를 말한다.__  
 L1-norm : 각 성분의 _변화량의 절대값_ 을 모두 더한다.  
 L2-norm : 피타고라스 정리를 이용해 _유클리드 거리_ 를 계산한다.  
 why? 기하학적 성질이 다르다.

In [15]:
def ll_norm(x):
    x_norm = np.abs(x)
    x_norm = np.sum(x_norm)
    return x_norm

def l2_norm(x):
    x_norm = x*x
    x_norm = np.sum(x_norm)
    x_norm = np.sqrt(x_norm)
    return x_norm

In [16]:
x = np.array([1,-2])
ll_norm(x)
l2_norm(x)

2.23606797749979

## Vector 사이의 거리, 각도, 내적 

 두 벡터 사이의 거리는 __노름과 뺄셈__ 을 이용한다.  
 두 벡터 사이의 각도는 __제 2 코사인 법칙__ 을 이용한다.  
 두 벡터 사이의 내적은 __정사영된 벡터의 길이__ 와 관련 있다.


In [22]:
x = np.array([2,4])
y = np.array([3,5])
print(ll_norm(x-y)) # 변화거리
print(l2_norm(x-y)) # 실제거리

2
1.4142135623730951


In [25]:
def angle(x,y):
    v = np.inner(x,y) / (l2_norm(x) * l2_norm(y))
    theta = np.arccos(v)
    return theta

In [26]:
x = np.array([2,4])
y = np.array([3,5])
print(angle(x,y)) 

0.07677189126977907
